[package]
name = "federation-integration-tests"
description = "Integration tests for datafusion-federation"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
publish = false

[dependencies]
anyhow = "1.0.98"
duckdb = "1.4.4"
datafusion-table-providers = { git = "https://github.com/spiceai/datafusion-table-providers.git", rev = "dc9c9a1e609f230d5870a975372a8bd1da953b9f", features = [
    "duckdb",
    "duckdb-federation",
] } # branch: spiceai-55-patches

datafusion = { workspace = true }
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros"] }
async-trait.workspace = true
tonic = "0.13"
futures.workspace = true
insta = { version = "1.42.0", features = ["filters"] }
chrono = "0.4.31"
datafusion-federation = { workspace = true, features = ["sql"] }
