[package]
name = "federation-integration-tests"
description = "Integration tests for datafusion-federation"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
publish = false

[dependencies]
anyhow = "1.0.98"
duckdb = "1.10503"
datafusion-table-providers = { git = "https://github.com/datafusion-contrib/datafusion-table-providers.git", rev = "9955a7b961602b9ad54a31265245628e71173edd", features = [
    "duckdb",
    "duckdb-federation",
] } # sgrebnov/spiceai-53

datafusion = { workspace = true }
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros"] }
async-trait.workspace = true
tonic = "0.13"
futures.workspace = true
insta = { version = "1.42.0", features = ["filters"] }
chrono = "0.4.31"
datafusion-federation = { workspace = true, features = ["sql"] }
